# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_has_only_valid_observations <- function(
  x,
  x_nm = NULL,
  call = NULL,
  expressions,
  fail_messages = NULL,
  pass_messages = NULL,
  col_nms = names(x),
  col_nm_set_list = NULL
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_has_only_valid_observations(
    x = x,
    x_nm = x_nm,
    call = call,
    expressions = expressions,
    fail_messages = fail_messages,
    pass_messages = pass_messages,
    col_nms = col_nms,
    col_nm_set_list = col_nm_set_list
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_is <- function(
  x,
  x_nm = NULL,
  call = NULL,
  env = NULL
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_is(
    x = x,
    x_nm = x_nm,
    call = call,
    env = env
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_is_all_equal <- function(
  x,
  x_nm = NULL,
  call = NULL,
  y,
  y_nm = NULL,
  all_equal_arg_list = NULL
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_is_all_equal(
    x = x,
    x_nm = x_nm,
    call = call,
    y = y,
    y_nm = y_nm,
    all_equal_arg_list = all_equal_arg_list
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_is_identical <- function(
  x,
  x_nm = NULL,
  call = NULL,
  y,
  y_nm = NULL
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_is_identical(
    x = x,
    x_nm = x_nm,
    call = call,
    y = y,
    y_nm = y_nm
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_is_like_template <- function(
  x,
  x_nm = NULL,
  call = NULL,
  template,
  compare = NULL
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_is_like_template(
    x = x,
    x_nm = x_nm,
    call = call,
    template = template,
    compare = compare
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

# generated by dbc::generate_report_function_wrapper_script.
# do no modify by hand!
#' @rdname assertions
#' @export
assert_dev_output_is_one_of <- function(
  x,
  x_nm = NULL,
  call = NULL,
  funs
) {
  dbc::handle_args_inplace()
  assertion_type <- "dev_output"
  report_df <- dbc::report_is_one_of(
    x = x,
    x_nm = x_nm,
    call = call,
    funs = funs
  )
  dbc::report_to_assertion(
    report_df = report_df,
    assertion_type = assertion_type,
    raise_error_call = call
  )
}

